[2024-11-27T21:53:28.899+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-27T21:53:28.905+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch_pipeline.extract_images scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-11-27T21:53:28.908+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch_pipeline.extract_images scheduled__2024-01-12T00:00:00+00:00 [queued]>
[2024-11-27T21:53:28.909+0700] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2024-11-27T21:53:28.916+0700] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_images> on 2024-01-12 00:00:00+00:00
[2024-11-27T21:53:28.918+0700] {standard_task_runner.py:72} INFO - Started process 33847 to run task
[2024-11-27T21:53:28.921+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'rocket_launch_pipeline', 'extract_images', 'scheduled__2024-01-12T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmo5rbjhq']
[2024-11-27T21:53:28.921+0700] {standard_task_runner.py:105} INFO - Job 99: Subtask extract_images
[2024-11-27T21:53:28.943+0700] {task_command.py:467} INFO - Running <TaskInstance: rocket_launch_pipeline.extract_images scheduled__2024-01-12T00:00:00+00:00 [running]> on host Web-container
[2024-11-27T21:53:28.976+0700] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='rocket_launch_pipeline' AIRFLOW_CTX_TASK_ID='extract_images' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-12T00:00:00+00:00'
[2024-11-27T21:53:28.976+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-27T21:53:28.976+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-27T21:53:28.976+0700] {logging_mixin.py:190} INFO - Current task name:extract_images state:running start_date:2024-11-27 14:53:28.905532+00:00
[2024-11-27T21:53:28.976+0700] {logging_mixin.py:190} INFO - Dag name:rocket_launch_pipeline and current dag run status:running
[2024-11-27T21:53:28.976+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-27T21:53:30.466+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-27T21:53:30.477+0700] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 33847. PIDs of all processes in the group: [33847]
[2024-11-27T21:53:30.477+0700] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 33847
[2024-11-27T21:53:30.477+0700] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-27T21:53:30.485+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/fawzan/airflow/dags/dag.py", line 37, in extract_images
    download_image(url)
  File "/home/fawzan/airflow/dags/dag.py", line 40, in download_image
    response = requests.get(url)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
  File "/home/fawzan/airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-27T21:53:30.506+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-27T21:53:30.506+0700] {logging_mixin.py:190} INFO - Task start:2024-11-27 14:53:28.905532+00:00 end:2024-11-27 14:53:30.505734+00:00 duration:1.600202
[2024-11-27T21:53:30.507+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_images> dag:<DAG: rocket_launch_pipeline> dagrun:<DagRun rocket_launch_pipeline @ 2024-01-12 00:00:00+00:00: scheduled__2024-01-12T00:00:00+00:00, state:running, queued_at: 2024-11-06 11:16:06.991094+00:00. externally triggered: False>
[2024-11-27T21:53:30.507+0700] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-27T21:53:30.507+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=rocket_launch_pipeline, task_id=extract_images, run_id=scheduled__2024-01-12T00:00:00+00:00, execution_date=20240112T000000, start_date=20241127T145328, end_date=20241127T145330
[2024-11-27T21:53:30.524+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
